/**
 * Shared Event Handler Utilities
 *
 * Event name translations and normalization used across all languages.
 */

/**
 * Common event names translated across languages.
 * Used by tokenizers to normalize event names to English.
 */
export const eventNameTranslations: Record<string, Record<string, string>> = {
  // Korean event names → English
  ko: {
    '클릭': 'click',
    '입력': 'input',
    '변경': 'change',
    '제출': 'submit',
    '키다운': 'keydown',
    '키업': 'keyup',
    '마우스오버': 'mouseover',
    '마우스아웃': 'mouseout',
    '포커스': 'focus',
    '블러': 'blur',
    '로드': 'load',
    '스크롤': 'scroll',
  },
  // Japanese event names → English
  ja: {
    'クリック': 'click',
    '入力': 'input',
    '変更': 'change',
    '送信': 'submit',
    'キーダウン': 'keydown',
    'キーアップ': 'keyup',
    'キープレス': 'keypress',
    'マウスオーバー': 'mouseover',
    'マウスアウト': 'mouseout',
    'フォーカス': 'focus',
    'ブラー': 'blur',
    'ロード': 'load',
    'スクロール': 'scroll',
  },
  // Arabic event names → English
  ar: {
    'النقر': 'click',
    'نقر': 'click',
    'الإدخال': 'input',
    'إدخال': 'input',
    'التغيير': 'change',
    'تغيير': 'change',
    'الإرسال': 'submit',
    'إرسال': 'submit',
    'ضغط المفتاح': 'keydown',
    'رفع المفتاح': 'keyup',
    'تمرير الماوس': 'mouseover',
    'التركيز': 'focus',
    'تحميل': 'load',
    'تمرير': 'scroll',
  },
  // Spanish event names → English
  es: {
    'clic': 'click',
    'click': 'click',
    'entrada': 'input',
    'cambio': 'change',
    'envío': 'submit',
    'enviar': 'submit',
    'tecla abajo': 'keydown',
    'tecla arriba': 'keyup',
    'ratón encima': 'mouseover',
    'ratón fuera': 'mouseout',
    'enfoque': 'focus',
    'desenfoque': 'blur',
    'carga': 'load',
    'desplazamiento': 'scroll',
  },
  // Turkish event names → English
  tr: {
    'tıklama': 'click',
    'tıkla': 'click',
    'tık': 'click',
    'giriş': 'input',
    'girdi': 'input',
    'değişiklik': 'change',
    'değişim': 'change',
    'gönderme': 'submit',
    'gönder': 'submit',
    'tuşbasma': 'keydown',
    'tuşbırakma': 'keyup',
    'fareiçinde': 'mouseover',
    'faredışında': 'mouseout',
    'odaklanma': 'focus',
    'odak': 'focus',
    'bulanıklık': 'blur',
    'yükleme': 'load',
    'kaydırma': 'scroll',
  },
  // Portuguese event names → English
  pt: {
    'clique': 'click',
    'clicar': 'click',
    'click': 'click',
    'entrada': 'input',
    'inserir': 'input',
    'mudança': 'change',
    'mudanca': 'change',
    'alterar': 'change',
    'envio': 'submit',
    'enviar': 'submit',
    'tecla baixo': 'keydown',
    'tecla cima': 'keyup',
    'pressionar tecla': 'keydown',
    'soltar tecla': 'keyup',
    'mouse sobre': 'mouseover',
    'mouse fora': 'mouseout',
    'foco': 'focus',
    'focar': 'focus',
    'desfoque': 'blur',
    'desfocar': 'blur',
    'carregar': 'load',
    'carregamento': 'load',
    'rolagem': 'scroll',
    'rolar': 'scroll',
  },
  // Chinese event names → English
  zh: {
    '点击': 'click',
    '单击': 'click',
    '双击': 'dblclick',
    '输入': 'input',
    '改变': 'change',
    '变化': 'change',
    '变更': 'change',
    '提交': 'submit',
    '发送': 'submit',
    '按键': 'keydown',
    '键入': 'keydown',
    '松键': 'keyup',
    '鼠标进入': 'mouseover',
    '鼠标移入': 'mouseover',
    '鼠标离开': 'mouseout',
    '鼠标移出': 'mouseout',
    '焦点': 'focus',
    '聚焦': 'focus',
    '失焦': 'blur',
    '模糊': 'blur',
    '加载': 'load',
    '载入': 'load',
    '滚动': 'scroll',
  },
  // French event names → English
  fr: {
    'clic': 'click',
    'cliquer': 'click',
    'click': 'click',
    'saisie': 'input',
    'entrée': 'input',
    'changement': 'change',
    'changer': 'change',
    'soumettre': 'submit',
    'soumission': 'submit',
    'envoi': 'submit',
    'touche bas': 'keydown',
    'touche haut': 'keyup',
    'souris dessus': 'mouseover',
    'souris dehors': 'mouseout',
    'focus': 'focus',
    'focaliser': 'focus',
    'défocus': 'blur',
    'défocaliser': 'blur',
    'chargement': 'load',
    'charger': 'load',
    'défilement': 'scroll',
    'défiler': 'scroll',
  },
  // German event names → English
  de: {
    'klick': 'click',
    'klicken': 'click',
    'click': 'click',
    'eingabe': 'input',
    'eingeben': 'input',
    'änderung': 'change',
    'ändern': 'change',
    'absenden': 'submit',
    'einreichen': 'submit',
    'taste runter': 'keydown',
    'taste hoch': 'keyup',
    'maus über': 'mouseover',
    'maus raus': 'mouseout',
    'fokus': 'focus',
    'fokussieren': 'focus',
    'defokussieren': 'blur',
    'unschärfe': 'blur',
    'laden': 'load',
    'ladung': 'load',
    'scrollen': 'scroll',
    'blättern': 'scroll',
  },
  // Indonesian event names → English
  id: {
    'klik': 'click',
    'click': 'click',
    'masukan': 'input',
    'input': 'input',
    'ubah': 'change',
    'perubahan': 'change',
    'kirim': 'submit',
    'tekan tombol': 'keydown',
    'lepas tombol': 'keyup',
    'mouse masuk': 'mouseover',
    'mouse keluar': 'mouseout',
    'fokus': 'focus',
    'blur': 'blur',
    'muat': 'load',
    'memuat': 'load',
    'gulir': 'scroll',
    'menggulir': 'scroll',
  },
  // Quechua event names → English (loanwords with native adaptations)
  qu: {
    'click': 'click',
    'ñit\'iy': 'click',
    'yaykuy': 'input',
    'tikray': 'change',
    't\'ikray': 'change',
    'apachiy': 'submit',
    'kachay': 'submit',
    'llave uray': 'keydown',
    'llave hawa': 'keyup',
    'q\'away': 'focus',
    'mana q\'away': 'blur',
    'cargay': 'load',
    'apamuy': 'load',
    'muyuy': 'scroll',
  },
  // Swahili event names → English
  sw: {
    'bofya': 'click',
    'click': 'click',
    'kubofya': 'click',
    'ingiza': 'input',
    'kubadilisha': 'change',
    'mabadiliko': 'change',
    'tuma': 'submit',
    'kutuma': 'submit',
    'bonyeza chini': 'keydown',
    'bonyeza juu': 'keyup',
    'panya juu': 'mouseover',
    'panya nje': 'mouseout',
    'lenga': 'focus',
    'kulenga': 'focus',
    'blur': 'blur',
    'pakia': 'load',
    'kupakia': 'load',
    'sogeza': 'scroll',
    'kusogeza': 'scroll',
  },
};

/**
 * Normalize an event name to English.
 */
export function normalizeEventName(event: string, language: string): string {
  const translations = eventNameTranslations[language];
  if (translations && translations[event]) {
    return translations[event];
  }
  return event.toLowerCase();
}
