/**
 * Bundle Generator
 *
 * Core generator logic for creating minimal HyperFixi bundles.
 * Used by both CLI and Vite plugin.
 */

import type { BundleConfig, GeneratorOptions, GeneratedBundle, ValidationError } from './types';
import {
  COMMAND_IMPLEMENTATIONS,
  BLOCK_IMPLEMENTATIONS,
  STYLE_COMMANDS,
  ELEMENT_ARRAY_COMMANDS,
  getCommandImplementations,
  getBlockImplementations,
  type CodeFormat,
} from './templates';

/**
 * Generate bundle code from configuration
 *
 * @param config Bundle configuration
 * @returns Generated TypeScript code as a string
 */
export function generateBundleCode(config: GeneratorOptions): string {
  const {
    name,
    commands,
    blocks = [],
    htmxIntegration = false,
    globalName = 'hyperfixi',
    positionalExpressions = false,
    parserImportPath = '../parser/hybrid',
    autoInit = true,
    esModule = true,
    format = 'ts',
    maxLoopIterations = 1000,
  } = config;

  const needsStyleHelpers = commands.some(cmd => STYLE_COMMANDS.includes(cmd));
  const needsElementArrayHelper = commands.some(cmd => ELEMENT_ARRAY_COMMANDS.includes(cmd));
  const hasBlocks = blocks.length > 0;
  const hasReturn = commands.includes('return');

  // Get format-specific implementations
  const commandImpls = getCommandImplementations(format);
  const blockImpls = getBlockImplementations(format);

  const commandCases = commands
    .filter(cmd => commandImpls[cmd])
    .map(cmd => commandImpls[cmd])
    .join('\n');

  const blockCases = blocks
    .filter(block => blockImpls[block])
    .map(block => blockImpls[block])
    .join('\n');

  return `/**
 * HyperFixi ${name} Bundle (Auto-Generated)
 *
 * Generated by: @lokascript/core bundle-generator
 * Commands: ${commands.join(', ')}${blocks.length > 0 ? `\n * Blocks: ${blocks.join(', ')}` : ''}${positionalExpressions ? '\n * Positional expressions: enabled' : ''}
 *
 * DO NOT EDIT - Regenerate with the build script.
 */

// =============================================================================
// MODULAR PARSER IMPORTS
// =============================================================================

import { HybridParser } from '${parserImportPath}/parser-core';
import type { ASTNode, CommandNode, EventNode${hasBlocks ? ', BlockNode' : ''} } from '${parserImportPath}/ast-types';

// =============================================================================
// RUNTIME
// =============================================================================

interface Context {
  me: Element;
  event?: Event;
  it?: any;
  you?: Element;
  locals: Map<string, any>;
}

const globalVars = new Map<string, any>();
${hasBlocks ? `const MAX_LOOP_ITERATIONS = ${maxLoopIterations};` : ''}

async function evaluate(node: ASTNode, ctx: Context): Promise<any> {
  switch (node.type) {
    case 'literal': return node.value;

    case 'identifier':
      if (node.value === 'me' || node.value === 'my') return ctx.me;
      if (node.value === 'it') return ctx.it;
      if (node.value === 'you') return ctx.you;
      if (node.value === 'event') return ctx.event;
      if (node.value === 'body') return document.body;
      if (node.value === 'document') return document;
      if (node.value === 'window') return window;
      if (ctx.locals.has(node.value)) return ctx.locals.get(node.value);
      if (node.value in (ctx.me as any)) return (ctx.me as any)[node.value];
      return node.value;

    case 'variable':
      if (node.scope === 'local') return ctx.locals.get(node.name.slice(1));
      const gName = node.name.slice(1);
      if (globalVars.has(gName)) return globalVars.get(gName);
      return (window as any)[node.name];

    case 'selector':
      const elements = document.querySelectorAll(node.value);
      return elements.length === 1 ? elements[0] : Array.from(elements);

    case 'binary':
      return evaluateBinary(node, ctx);

    case 'possessive':
    case 'member':
      const obj = await evaluate(node.object, ctx);
      if (obj == null) return undefined;
      const prop = node.computed ? await evaluate(node.property, ctx) : node.property;
      return obj[prop];

    case 'call': {
      let callContext: any = null;
      let callee: any;

      if (node.callee.type === 'member' || node.callee.type === 'possessive') {
        callContext = await evaluate(node.callee.object, ctx);
        const p = node.callee.computed
          ? await evaluate(node.callee.property, ctx)
          : node.callee.property;
        callee = callContext?.[p];
      } else {
        callee = await evaluate(node.callee, ctx);
      }

      const args = await Promise.all(node.args.map((a: ASTNode) => evaluate(a, ctx)));
      if (typeof callee === 'function') return callee.apply(callContext, args);
      return undefined;
    }
${
  positionalExpressions
    ? `
    case 'positional':
      return evaluatePositional(node, ctx);
`
    : ''
}
    default: return undefined;
  }
}

async function evaluateBinary(node: ASTNode, ctx: Context): Promise<any> {
  if (node.operator === 'has') {
    const left = await evaluate(node.left, ctx);
    if (left instanceof Element && node.right.type === 'selector' && node.right.value.startsWith('.')) {
      return left.classList.contains(node.right.value.slice(1));
    }
    return false;
  }

  const left = await evaluate(node.left, ctx);
  const right = await evaluate(node.right, ctx);

  switch (node.operator) {
    case '+': return left + right;
    case '-': return left - right;
    case '*': return left * right;
    case '/': return left / right;
    case '%': return left % right;
    case '==': case 'is': return left == right;
    case '!=': case 'is not': return left != right;
    case '<': return left < right;
    case '>': return left > right;
    case '<=': return left <= right;
    case '>=': return left >= right;
    case 'and': case '&&': return left && right;
    case 'or': case '||': return left || right;
    case 'contains': case 'includes':
      if (typeof left === 'string') return left.includes(right);
      if (Array.isArray(left)) return left.includes(right);
      if (left instanceof Element) return left.contains(right);
      return false;
    case 'matches':
      if (left instanceof Element) return left.matches(right);
      if (typeof left === 'string') return new RegExp(right).test(left);
      return false;
    default: return undefined;
  }
}
${
  positionalExpressions
    ? `
function evaluatePositional(node: ASTNode, ctx: Context): Element | null {
  const target = node.target;
  let elements: Element[] = [];

  let selector: string | null = null;
  if (target.type === 'selector') {
    selector = target.value;
  } else if (target.type === 'identifier') {
    selector = target.value;
  } else if (target.type === 'htmlSelector') {
    selector = target.value;
  }
  if (selector) {
    elements = Array.from(document.querySelectorAll(selector));
  }

  switch (node.position) {
    case 'first': return elements[0] || null;
    case 'last': return elements[elements.length - 1] || null;
    case 'next': return ctx.me.nextElementSibling;
    case 'previous': return ctx.me.previousElementSibling;
    case 'closest': return target.value ? ctx.me.closest(target.value) : null;
    case 'parent': return ctx.me.parentElement;
    default: return elements[0] || null;
  }
}
`
    : ''
}
// =============================================================================
// COMMAND EXECUTOR
// =============================================================================

${
  needsStyleHelpers
    ? `
const isStyleProp = (prop: string) => prop?.startsWith('*');
const getStyleName = (prop: string) => prop.substring(1);
const setStyleProp = (el: Element, prop: string, value: any): boolean => {
  if (!isStyleProp(prop)) return false;
  (el as HTMLElement).style.setProperty(getStyleName(prop), String(value));
  return true;
};
`
    : ''
}

${
  needsElementArrayHelper
    ? `
const toElementArray = (val: any): Element[] => {
  if (Array.isArray(val)) return val.filter(e => e instanceof Element);
  if (val instanceof Element) return [val];
  if (typeof val === 'string') return Array.from(document.querySelectorAll(val));
  return [];
};
`
    : ''
}

async function executeCommand(cmd: CommandNode, ctx: Context): Promise<any> {
  const getTarget = async (): Promise<Element[]> => {
    if (!cmd.target) return [ctx.me];
    const t = await evaluate(cmd.target, ctx);
    if (Array.isArray(t)) return t;
    if (t instanceof Element) return [t];
    if (typeof t === 'string') return Array.from(document.querySelectorAll(t));
    return [ctx.me];
  };

  const getClassName = (node: any): string => {
    if (!node) return '';
    if (node.type === 'selector') return node.value.slice(1);
    if (node.type === 'string' || node.type === 'literal') {
      const val = node.value;
      return typeof val === 'string' && val.startsWith('.') ? val.slice(1) : String(val);
    }
    if (node.type === 'identifier') return node.value;
    return '';
  };

  switch (cmd.name) {
${commandCases}

    default:
      console.warn(\`${name} bundle: Unknown command '\${cmd.name}'\`);
      return null;
  }
}
${
  hasBlocks
    ? `
// =============================================================================
// BLOCK EXECUTOR
// =============================================================================

async function executeBlock(block: BlockNode, ctx: Context): Promise<any> {
  switch (block.type) {
${blockCases}

    default:
      console.warn(\`${name} bundle: Unknown block '\${block.type}'\`);
      return null;
  }
}
`
    : ''
}
// =============================================================================
// SEQUENCE EXECUTOR
// =============================================================================

async function executeSequence(nodes: ASTNode[], ctx: Context): Promise<any> {
  let result: any;
  for (const node of nodes) {
    if (node.type === 'command') {
      result = await executeCommand(node as CommandNode, ctx);
    }${
      hasBlocks
        ? ` else if (['if', 'repeat', 'for', 'while', 'fetch'].includes(node.type)) {
      result = await executeBlock(node as BlockNode, ctx);
    }`
        : ''
    }
  }
  return result;
}
${
  hasBlocks
    ? `
async function executeSequenceWithBlocks(nodes: ASTNode[], ctx: Context): Promise<any> {
  try {
    return await executeSequence(nodes, ctx);
  } catch (e: any) {
    if (e?.type === 'return') throw e;
    throw e;
  }
}
`
    : ''
}
async function executeAST(ast: ASTNode, me: Element, event?: Event): Promise<any> {
  const ctx: Context = { me, event, locals: new Map() };

  if (ast.type === 'sequence') {
    ${hasReturn || hasBlocks ? "try { return await executeSequence(ast.commands, ctx); } catch (e: any) { if (e?.type === 'return') return e.value; throw e; }" : 'return executeSequence(ast.commands, ctx);'}
  }

  if (ast.type === 'event') {
    const eventNode = ast as EventNode;
    const eventName = eventNode.event;

    if (eventName === 'init') {
      ${hasReturn || hasBlocks ? "try { await executeSequence(eventNode.body, ctx); } catch (e: any) { if (e?.type !== 'return') throw e; }" : 'await executeSequence(eventNode.body, ctx);'}
      return;
    }

    const target = eventNode.filter ? await evaluate(eventNode.filter, ctx) : me;
    const targetEl = target instanceof Element ? target : me;
    const mods = eventNode.modifiers;

    let handler = async (e: Event) => {
      if (mods.prevent) e.preventDefault();
      if (mods.stop) e.stopPropagation();

      const handlerCtx: Context = {
        me, event: e,
        you: e.target instanceof Element ? e.target : undefined,
        locals: new Map(),
      };
      ${hasReturn || hasBlocks ? "try { await executeSequence(eventNode.body, handlerCtx); } catch (err: any) { if (err?.type !== 'return') throw err; }" : 'await executeSequence(eventNode.body, handlerCtx);'}
    };

    if (mods.debounce) {
      let timeout: any;
      const orig = handler;
      handler = async (e: Event) => {
        clearTimeout(timeout);
        timeout = setTimeout(() => orig(e), mods.debounce);
      };
    }

    if (mods.throttle) {
      let lastCall = 0;
      const orig = handler;
      handler = async (e: Event) => {
        const now = Date.now();
        if (now - lastCall >= mods.throttle!) {
          lastCall = now;
          await orig(e);
        }
      };
    }

    targetEl.addEventListener(eventName, handler, { once: !!mods.once });
    return;
  }

  return null;
}

// =============================================================================
// DOM PROCESSOR
// =============================================================================

function processElement(el: Element): void {
  const code = el.getAttribute('_');
  if (!code) return;

  try {
    const parser = new HybridParser(code);
    const ast = parser.parse();
    executeAST(ast, el);
  } catch (err) {
    console.error('HyperFixi ${name} error:', err, 'Code:', code);
  }
}

function processElements(root: Element | Document = document): void {
  const elements = root.querySelectorAll('[_]');
  elements.forEach(processElement);
}

// =============================================================================
// PUBLIC API
// =============================================================================

const api = {
  version: '1.0.0-${name.toLowerCase().replace(/\s+/g, '-')}',

  parse(code: string): ASTNode {
    const parser = new HybridParser(code);
    return parser.parse();
  },

  async execute(code: string, element?: Element): Promise<any> {
    const me = element || document.body;
    const parser = new HybridParser(code);
    const ast = parser.parse();
    return executeAST(ast, me);
  },

  run: async (code: string, element?: Element) => api.execute(code, element),
  eval: async (code: string, element?: Element) => api.execute(code, element),

  init: processElements,
  process: processElements,

  commands: ${JSON.stringify(commands)},
  ${blocks.length > 0 ? `blocks: ${JSON.stringify(blocks)},` : ''}
  parserName: 'hybrid',
};

// =============================================================================
// AUTO-INITIALIZE
// =============================================================================
${
  autoInit
    ? `
if (typeof window !== 'undefined') {
  (window as any).${globalName} = api;
  (window as any)._hyperscript = api;

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => processElements());
  } else {
    processElements();
  }
${
  htmxIntegration
    ? `
  // HTMX integration
  document.addEventListener('htmx:afterSettle', (e: Event) => {
    const target = (e as CustomEvent).detail?.target;
    if (target) processElements(target);
  });
`
    : ''
}
}
`
    : ''
}
${
  esModule
    ? `
export default api;
export { api, processElements };
`
    : ''
}`;
}

/**
 * Generate a bundle with metadata and warnings
 *
 * @param config Bundle configuration (can include GeneratorOptions for validation)
 * @returns Generated bundle with metadata
 * @throws Error if strict validation is enabled and unknown commands/blocks are found
 */
export function generateBundle(config: BundleConfig & Partial<GeneratorOptions>): GeneratedBundle {
  const warnings: string[] = [];
  const errors: ValidationError[] = [];
  const strict = (config as GeneratorOptions).validation?.strict ?? false;

  // Check for unknown commands
  const unknownCommands = config.commands.filter(cmd => !COMMAND_IMPLEMENTATIONS[cmd]);
  for (const cmd of unknownCommands) {
    const error: ValidationError = {
      type: 'unknown-command',
      message: `Unknown command '${cmd}' will not be included`,
      name: cmd,
    };
    errors.push(error);
    warnings.push(error.message);
  }

  // Check for unknown blocks
  const unknownBlocks = (config.blocks || []).filter(block => !BLOCK_IMPLEMENTATIONS[block]);
  for (const block of unknownBlocks) {
    const error: ValidationError = {
      type: 'unknown-block',
      message: `Unknown block '${block}' will not be included`,
      name: block,
    };
    errors.push(error);
    warnings.push(error.message);
  }

  // In strict mode, throw an error if any validation errors exist
  if (strict && errors.length > 0) {
    const errorMessages = errors.map(e => e.message).join('; ');
    throw new Error(`Bundle generation failed (strict mode): ${errorMessages}`);
  }

  const code = generateBundleCode(config as GeneratorOptions);

  return {
    code,
    commands: config.commands.filter(cmd => COMMAND_IMPLEMENTATIONS[cmd]),
    blocks: (config.blocks || []).filter(block => BLOCK_IMPLEMENTATIONS[block]),
    positional: config.positionalExpressions || false,
    warnings,
    errors,
  };
}
