name: Feature Request
description: Suggest a new feature or improvement for HyperFixi / LokaScript
title: '[Feature]: '
labels: ['feature-request']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What's the use case?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I'd like to be able to write:
        ```html
        <button _="on click ...">
        ```
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package would this feature belong to?
      options:
        - '@hyperfixi/core'
        - '@hyperfixi/vite-plugin'
        - '@lokascript/semantic'
        - '@lokascript/i18n'
        - '@lokascript/mcp-server'
        - 'New package'
        - 'Not sure'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples.
