/**
 * Vite Plugin Types
 *
 * Type definitions for the HyperFixi Vite plugin.
 */

/**
 * Options for the HyperFixi Vite plugin
 */
export interface HyperfixiPluginOptions {
  /**
   * Bundle generation mode:
   * - 'interpret': Generate minimal bundle with parser (default, ~8KB gzip)
   * - 'compile': Pre-compile hyperscript to JS at build time (~500 bytes gzip)
   *
   * Compile mode limitations:
   * - No dynamic hyperscript (runtime execute() won't work)
   * - No block commands (if, for, repeat, while, fetch)
   * - HTML must be transformed to use data-h attributes
   *
   * Use compile mode when:
   * - Bundle size is critical (<1KB target)
   * - All hyperscript is static (no dynamic generation)
   * - Only simple commands are used (toggle, add, remove, set, etc.)
   */
  mode?: 'interpret' | 'compile';

  /**
   * File patterns to scan for hyperscript usage.
   * Defaults to common web file extensions.
   */
  include?: RegExp | string[];

  /**
   * File patterns to exclude from scanning.
   * Defaults to node_modules.
   */
  exclude?: RegExp | string[];

  /**
   * Extra commands to always include in the bundle.
   * Use this for dynamically generated hyperscript that can't be detected.
   */
  extraCommands?: string[];

  /**
   * Extra blocks to always include in the bundle.
   */
  extraBlocks?: string[];

  /**
   * Always include positional expressions (first, last, next, closest, parent).
   * Set to true if your dynamic code uses these.
   */
  positional?: boolean;

  /**
   * Enable HTMX integration (auto-process after htmx:afterSettle).
   */
  htmx?: boolean;

  /**
   * Development mode fallback strategy.
   * - 'hybrid-complete': Use pre-built hybrid-complete bundle for faster dev (default)
   * - 'full': Use full bundle for complete compatibility
   * - 'auto': Generate minimal bundle even in dev
   */
  devFallback?: 'hybrid-complete' | 'full' | 'auto';

  /**
   * Global variable name for the hyperfixi API.
   * Defaults to 'hyperfixi'.
   */
  globalName?: string;

  /**
   * Bundle name for generated code comments.
   * Defaults to 'ViteAutoGenerated'.
   */
  bundleName?: string;

  /**
   * Enable verbose logging during development.
   */
  debug?: boolean;

  // =========================================================================
  // Multilingual Semantic Options
  // =========================================================================

  /**
   * Enable semantic parsing for multilingual support.
   * - false: No semantic parsing (default, current behavior)
   * - true: Auto-detect languages from templates
   * - 'en': English semantic only (synonyms, flexible syntax)
   * - 'auto': Same as true
   */
  semantic?: boolean | 'en' | 'auto';

  /**
   * Explicit language list (overrides auto-detection).
   * Use ISO 639-1 codes: 'en', 'es', 'ja', 'ko', 'zh', 'ar', etc.
   */
  languages?: string[];

  /**
   * Regional bundle shorthand (alternative to explicit languages).
   * - 'western': en, es, pt, fr, de
   * - 'east-asian': ja, zh, ko
   * - 'priority': 11 most common languages
   * - 'all': All 13 supported languages
   */
  region?: 'western' | 'east-asian' | 'priority' | 'all';

  /**
   * Enable grammar transformation for native word order.
   * When true, semantic is automatically enabled.
   * Adds support for SOV (Japanese, Korean) and VSO (Arabic) word orders.
   */
  grammar?: boolean;

  /**
   * Always include these languages in addition to detected ones.
   * Useful for dynamic content not detectable at build time.
   */
  extraLanguages?: string[];
}

/**
 * Usage information detected from a single file
 */
export interface FileUsage {
  /** Commands used in this file */
  commands: Set<string>;

  /** Block types used (if, repeat, for, while, fetch) */
  blocks: Set<string>;

  /** Whether positional expressions are used */
  positional: boolean;

  /** Non-English languages detected in hyperscript (ISO 639-1 codes) */
  detectedLanguages: Set<string>;
}

/**
 * Aggregated usage information across all files
 */
export interface AggregatedUsage {
  /** All commands detected across all files */
  commands: Set<string>;

  /** All blocks detected across all files */
  blocks: Set<string>;

  /** Whether any file uses positional expressions */
  positional: boolean;

  /** All non-English languages detected across all files */
  detectedLanguages: Set<string>;

  /** Map of file paths to their usage */
  fileUsage: Map<string, FileUsage>;
}

/**
 * Information about a script that needs compilation
 */
export interface ScriptLocation {
  /** File path where the script was found */
  file: string;

  /** The hyperscript code */
  script: string;

  /** Line number in the file (for source maps) */
  line?: number;

  /** Column number in the file */
  column?: number;
}

/**
 * Aggregated scripts for compilation mode
 */
export interface AggregatedScripts {
  /** All unique scripts found across all files */
  scripts: Map<string, ScriptLocation[]>;

  /** Map of file paths to scripts in that file */
  fileScripts: Map<string, string[]>;
}
