/**
 * Vite Plugin Types
 *
 * Type definitions for the HyperFixi Vite plugin.
 */

/**
 * Options for the HyperFixi Vite plugin
 */
export interface HyperfixiPluginOptions {
  /**
   * File patterns to scan for hyperscript usage.
   * Defaults to common web file extensions.
   */
  include?: RegExp | string[];

  /**
   * File patterns to exclude from scanning.
   * Defaults to node_modules.
   */
  exclude?: RegExp | string[];

  /**
   * Extra commands to always include in the bundle.
   * Use this for dynamically generated hyperscript that can't be detected.
   */
  extraCommands?: string[];

  /**
   * Extra blocks to always include in the bundle.
   */
  extraBlocks?: string[];

  /**
   * Always include positional expressions (first, last, next, closest, parent).
   * Set to true if your dynamic code uses these.
   */
  positional?: boolean;

  /**
   * Enable HTMX integration (auto-process after htmx:afterSettle).
   */
  htmx?: boolean;

  /**
   * Development mode fallback strategy.
   * - 'hybrid-complete': Use pre-built hybrid-complete bundle for faster dev (default)
   * - 'full': Use full bundle for complete compatibility
   * - 'auto': Generate minimal bundle even in dev
   */
  devFallback?: 'hybrid-complete' | 'full' | 'auto';

  /**
   * Global variable name for the hyperfixi API.
   * Defaults to 'hyperfixi'.
   */
  globalName?: string;

  /**
   * Bundle name for generated code comments.
   * Defaults to 'ViteAutoGenerated'.
   */
  bundleName?: string;

  /**
   * Enable verbose logging during development.
   */
  debug?: boolean;
}

/**
 * Usage information detected from a single file
 */
export interface FileUsage {
  /** Commands used in this file */
  commands: Set<string>;

  /** Block types used (if, repeat, for, while, fetch) */
  blocks: Set<string>;

  /** Whether positional expressions are used */
  positional: boolean;
}

/**
 * Aggregated usage information across all files
 */
export interface AggregatedUsage {
  /** All commands detected across all files */
  commands: Set<string>;

  /** All blocks detected across all files */
  blocks: Set<string>;

  /** Whether any file uses positional expressions */
  positional: boolean;

  /** Map of file paths to their usage */
  fileUsage: Map<string, FileUsage>;
}
