import { defineConfig } from 'tsup';

export default defineConfig([
  // Node.js builds (CJS + ESM)
  {
    entry: ['src/index.ts'],
    format: ['cjs', 'esm'],
    dts: true,
    splitting: false,
    sourcemap: true,
    clean: true,
      },
  // Browser bundle (IIFE) - Full 13-language bundle
  // Output: hyperfixi-semantic.browser.global.js
  {
    entry: ['src/browser.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemantic',
    minify: true,
    sourcemap: true,
    platform: 'browser',
        outExtension() {
      return { js: '.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      // Disable tree-shaking for full bundle to preserve language registration side effects
      options.treeShaking = false;
    },
  },
  // English-only browser bundle (IIFE) - Minimal bundle
  // Output: hyperfixi-semantic.browser-en.global.js
  {
    entry: ['src/browser-en.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticEn',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.en.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Spanish + English browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-es-en.global.js
  {
    entry: ['src/browser-es-en.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticEsEn',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.es-en.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Spanish-only browser bundle (IIFE) - Minimal single-language bundle
  // Output: hyperfixi-semantic.browser-es.es.global.js
  // Size: ~70 KB (smallest possible for Spanish)
  {
    entry: ['src/browser-es.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticEs',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.es.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Turkish-only browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-tr.tr.global.js
  // Generated by: node scripts/generate-bundle.mjs tr
  {
    entry: ['src/browser-tr.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticTr',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.tr.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Western languages browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-western.western.global.js
  // Languages: en, es, pt, fr, de (~150 KB)
  {
    entry: ['src/browser-western.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticWestern',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.western.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // East Asian languages browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-east-asian.east-asian.global.js
  // Languages: ja, zh, ko (~130 KB)
  {
    entry: ['src/browser-east-asian.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticEastAsian',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.east-asian.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Priority languages browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-priority.priority.global.js
  // Languages: All 11 priority languages (~280 KB)
  {
    entry: ['src/browser-priority.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticPriority',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.priority.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Lazy loading browser bundle (IIFE) - No languages pre-registered
  // Output: hyperfixi-semantic.browser-lazy.lazy.global.js
  // Languages are loaded on-demand via loadLanguage()
  {
    entry: ['src/browser-lazy.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticLazy',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.lazy.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Core browser bundle (IIFE) - No languages, CDN/URL-based loading
  // Output: hyperfixi-semantic.browser-core.core.global.js
  // Languages loaded via loadLanguageFromUrl() or self-registering script tags
  // Size: ~45 KB (infrastructure only)
  {
    entry: ['src/browser-core.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticCore',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.core.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Japanese browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-ja.ja.global.js
  // Generated by: node scripts/generate-bundle.mjs ja
  {
    entry: ['src/browser-ja.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticJa',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.ja.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Arabic browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-ar.ar.global.js
  // Generated by: node scripts/generate-bundle.mjs ar
  {
    entry: ['src/browser-ar.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticAr',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.ar.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Korean browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-ko.ko.global.js
  // Generated by: node scripts/generate-bundle.mjs ko
  {
    entry: ['src/browser-ko.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticKo',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.ko.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Chinese browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-zh.zh.global.js
  // Generated by: node scripts/generate-bundle.mjs zh
  {
    entry: ['src/browser-zh.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticZh',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.zh.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Portuguese browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-pt.pt.global.js
  // Generated by: node scripts/generate-bundle.mjs pt
  {
    entry: ['src/browser-pt.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticPt',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.pt.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // French browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-fr.fr.global.js
  // Generated by: node scripts/generate-bundle.mjs fr
  {
    entry: ['src/browser-fr.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticFr',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.fr.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // German browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-de.de.global.js
  // Generated by: node scripts/generate-bundle.mjs de
  {
    entry: ['src/browser-de.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticDe',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.de.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Indonesian browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-id.id.global.js
  // Generated by: node scripts/generate-bundle.mjs id
  {
    entry: ['src/browser-id.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticId',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.id.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Quechua browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-qu.qu.global.js
  // Generated by: node scripts/generate-bundle.mjs qu
  {
    entry: ['src/browser-qu.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticQu',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.qu.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Swahili browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-sw.sw.global.js
  // Generated by: node scripts/generate-bundle.mjs sw
  {
    entry: ['src/browser-sw.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticSw',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.sw.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // English + Turkish browser bundle (IIFE)
  // Output: hyperfixi-semantic.browser-en-tr.en-tr.global.js
  // Generated by: node scripts/generate-bundle.mjs en tr
  {
    entry: ['src/browser-en-tr.ts'],
    outDir: 'dist',
    format: ['iife'],
    globalName: 'LokaScriptSemanticEnTr',
    minify: true,
    sourcemap: false,
    platform: 'browser',
        outExtension() {
      return { js: '.en-tr.global.js' };
    },
    esbuildOptions(options) {
      options.target = 'es2020';
      options.treeShaking = true;
    },
  },
  // Individual language modules (ESM) for npm tree-shaking
  // These allow: import '@lokascript/semantic/languages/en'
  {
    entry: {
      'languages/en': 'src/languages/en.ts',
      'languages/es': 'src/languages/es.ts',
      'languages/ja': 'src/languages/ja.ts',
      'languages/ar': 'src/languages/ar.ts',
      'languages/ko': 'src/languages/ko.ts',
      'languages/zh': 'src/languages/zh.ts',
      'languages/tr': 'src/languages/tr.ts',
      'languages/pt': 'src/languages/pt.ts',
      'languages/fr': 'src/languages/fr.ts',
      'languages/de': 'src/languages/de.ts',
      'languages/id': 'src/languages/id.ts',
      'languages/qu': 'src/languages/qu.ts',
      'languages/sw': 'src/languages/sw.ts',
    },
    format: ['esm'],
    dts: true,
    splitting: false,
    sourcemap: true,
      },
]);
